/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package post_rian;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.awt.*;

/**
 *
 * @author Lenovo
 */
public class list_barang extends javax.swing.JFrame {

    DefaultTableModel tabModel;
    ResultSet RsSakit = null;

    public list_barang() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height = screenSize.height) / 20);
        tampilData();
        SetEditOff();
    }

    private void tampilData() {
        try {
            Object[] judul_kolom = {"ID", "Kode Barang", "Nama", "Harga Beli", "Harga Jual"};
            tabModel = new DefaultTableModel(null, judul_kolom);
            TableRs.setModel(tabModel);

            Connection conn = (Connection) koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            tabModel.getDataVector().removeAllElements();

            RsSakit = stt.executeQuery("SELECT\n"
                    + "	*, \n"
                    + "	barang.id, \n"
                    + "	barang.kode, \n"
                    + "	barang.nama_barang, \n"
                    + "	barang.harga_beli, \n"
                    + "	barang.harga_jual\n"
                    + "FROM\n"
                    + "	barang");
            while (RsSakit.next()) {
                Object[] data = {
                    RsSakit.getString("id"),
                    RsSakit.getString("kode"),
                    RsSakit.getString("nama_barang"),
                    RsSakit.getString("harga_beli"),
                    RsSakit.getString("harga_jual"),};
                tabModel.addRow(data);
            }

        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabelDokter = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRs = new javax.swing.JTable();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 32767));
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Data Entri");
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDokter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jLabelDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        TableRs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Kode Barang", "Nama", "Harga", "Qty"
            }
        ));
        TableRs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableRs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 870, 160));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 1068, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 250, -1));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 940, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/post_rian/icon/circled-left-2.png"))); // NOI18N
        jLabel2.setText("BACK HOME");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//manangani proses ketika button di click 


    private void TableRsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRsMouseClicked
        // TODO add your handling code here:
//        String jml;

        transaksi parent = new transaksi();
        parent.setVisible(true);

        parent.nambarang.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 2) + "");
        parent.kode_barang.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 0) + "");
        parent.harga.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 6) + "");

        String jml = (String) tabModel.getValueAt(TableRs.getSelectedRow(), 6);

        parent.harga.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 6) + "");
//        parent.jumlah.setEnabled(true);
//        jumlah.setEnabled(true);
//        String kl = ((String) parent.jumlah.getText() * jml);

        parent.totalBayar.setText(jml);

        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_TableRsMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        dashboard second = new dashboard();
        second.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list_barang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list_barang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list_barang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list_barang.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableRs;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDokter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

//add function list data java 
    //non aktif kan ketika program tidak di eksekusi
    private void SetEditOff() {

    }

    private void setEditOn() {

    }

    private void tblKeForm() {

//        jumlah.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 0) + "");
//
//        kode_barang.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 1) + "");
//        nama_barang.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 2) + "");
//        satuan.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 3) + "");
//        harga_jual.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 4) + "");
//        jTextNpwp.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 5) + "");
//        jComboBoxJentang.setSelectedItem(tabModel.getValueAt(TableRs.getSelectedRow(), 6) + "");
//        jTextFieldPlafon.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 7) + "");
    }

    private void BersihData() {

    }

}
