/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package post_rian;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.awt.*;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import static post_rian.print.foot;
import static post_rian.print.head;

/**
 *
 * @author Lenovo
 */
public class transaksi extends javax.swing.JFrame {

    DefaultTableModel tabModel;
    ResultSet RsSakit = null;

    public transaksi() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
                (screenSize.height = screenSize.height) / 20);
        tampilData();
        SetEditOff();
    }

    public void tampilData() {
        try {
            Object[] judul_kolom = {"ID", "Kode Barang ", "Nama ", "Qty", "Sub Total", "Status", "Created at", "Updated at"};
            tabModel = new DefaultTableModel(null, judul_kolom);
            TableRs.setModel(tabModel);

            Connection conn = (Connection) koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            tabModel.getDataVector().removeAllElements();

            RsSakit = stt.executeQuery("SELECT\n"
                    + "	transaksi.id, \n"
                    + "	barang.kode, \n"
                    + "	barang.nama_barang, \n"
                    + "	barang.harga_beli, \n"
                    + "	barang.harga_jual, \n"
                    + "	barang.satuan, \n"
                    + "	barang.jenis_barang, \n"
                    + "	transaksi.jumlah, \n"
                    + "	transaksi.total, \n"
                    + "	transaksi.`status`, \n"
                    + "	barang.id, \n"
                    + "	transaksi.created_at, \n"
                    + "	transaksi.updated_at\n"
                    + "FROM\n"
                    + "	transaksi\n"
                    + "	INNER JOIN\n"
                    + "	barang\n"
                    + "	ON \n"
                    + "		transaksi.barang_id = barang.id");
            while (RsSakit.next()) {
                Object[] data = {
                    RsSakit.getString("id"),
                    RsSakit.getString("kode"),
                    RsSakit.getString("nama_barang"),
                    RsSakit.getString("jumlah"),
                    RsSakit.getString("status"),
                    RsSakit.getString("harga_jual"),
                    RsSakit.getString("updated_at"),};
                tabModel.addRow(data);
            }

        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
        nambarang.setEnabled(false);
        totalBayar.setEnabled(false);
        harga.setEnabled(false);
        kode_barang.setEnabled(true);
        jumlah.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel3 = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelDiagnosa = new javax.swing.JLabel();
        jLabelHasil = new javax.swing.JLabel();
        jLabelUmur = new javax.swing.JLabel();
        kode_barang = new javax.swing.JTextField();
        nambarang = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jLabelDokter = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRs = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        Id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 32767));
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\dataentry\\src\\rianrs\\backgound.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Master Data Transaksi");
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNama.setText("Kode barang");
        getContentPane().add(jLabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        jLabelDiagnosa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDiagnosa.setText("Nama Barang");
        getContentPane().add(jLabelDiagnosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jLabelHasil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHasil.setText("Harga");
        getContentPane().add(jLabelHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabelUmur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUmur.setText("Jumlah");
        getContentPane().add(jLabelUmur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        kode_barang.setText(" ");
        kode_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kode_barangMouseEntered(evt);
            }
        });
        kode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_barangActionPerformed(evt);
            }
        });
        kode_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kode_barangKeyPressed(evt);
            }
        });
        getContentPane().add(kode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 190, -1));
        getContentPane().add(nambarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 200, -1));

        harga.setText(" ");
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 266, -1));

        jumlah.setText(" ");
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 266, -1));

        jLabelDokter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDokter.setText("Total Bayar");
        getContentPane().add(jLabelDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        totalBayar.setText(" ");
        getContentPane().add(totalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 191, -1));

        TableRs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "QTY", "Sub Total", "Status", "Created at", "Updated at"
            }
        ));
        TableRs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableRs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 870, 278));

        jButtonAdd.setBackground(new java.awt.Color(255, 255, 51));
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Add New");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jButtonSave.setText("Simpan");
        jButtonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSaveMouseClicked(evt);
            }
        });
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        Id.setText(" ");
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 270, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID Transaksi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 1068, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 250, -1));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/post_rian/icon/circled-left-2.png"))); // NOI18N
        jLabel2.setText("BACK HOME");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 100));

        jButton1.setText("Print");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//manangani proses ketika button di click 

//fungsi untuk tambah data
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        BersihData();
        kode_barang.requestFocus();
        Id.setEnabled(false);
        jButtonSave.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        jButtonDelete.setEnabled(false);
        setEditOn();
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void kode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_barangActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSaveMouseClicked
        // TODO add your handling code here:
        String Nambarang = nambarang.getText();
        String TotalBayar = totalBayar.getText();
        String Harga = harga.getText();
        String Kode_barang = kode_barang.getText();
        String Jumlah = jumlah.getText();

        try {
            Connection connection = (Connection) koneksi.koneksiDB();
            Statement stt = connection.createStatement();
            stt.executeUpdate("INSERT INTO ujian_visual.transaksi(barang_id,jumlah, total, status)"
                    + "        VALUES ('" + Kode_barang + "', '" + Jumlah + "', '" + Jumlah + "','" + 1 + "');");
            tampilData();
            setEditOn();
            BersihData();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Simpan data gagal\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSaveMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void TableRsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRsMouseClicked
        // TODO add your handling code here:
        setEditOn();
        tblKeForm();
        jButtonSave.setEnabled(false);
        jButtonUpdate.setEnabled(true);
    }//GEN-LAST:event_TableRsMouseClicked

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String IdRs = Id.getText();
        if (IdRs.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID Kosong Data Gagal Di Hapus.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int des = JOptionPane.showConfirmDialog(null, "Apakah anda yakin menghapus data ini ?", "Your title", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (des == 0) {
                try {
                    Connection connection = (Connection) koneksi.koneksiDB();
                    Statement stt = connection.createStatement();
                    stt.executeUpdate("DELETE from ujian_visual.transaksi where id ='" + IdRs + "'");
                    tampilData();
                    setEditOn();
                    BersihData();

                    JOptionPane.showMessageDialog(this, "Data berhasil hapus", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Simpan data gagal\n di hapus" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

        dashboard second = new dashboard();
        second.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void kode_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_barangKeyPressed
        list_barang ls = new list_barang();
        ls.setVisible(true);

        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_kode_barangKeyPressed

    private void kode_barangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kode_barangMouseEntered

    }//GEN-LAST:event_kode_barangMouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        PrinterJob pj = PrinterJob.getPrinterJob();

        PageFormat pf = pj.defaultPage();
        Paper paper = new Paper();
        double margin = 20; // half inch
        paper.setImageableArea(margin, margin - 15, paper.getWidth() - margin * 2, paper.getHeight()
                - margin * 2);
        pf.setPaper(paper);

        if (pj.printDialog()) {
            try {
                JEditorPane text = new JEditorPane("text/html", ""
                        + "<center style='font-family: monospace;font-size: 10;'>"
                        + "<h3>STRUK PEMBELIAN LISTRIK PRABAYAR</h3>"
                        + "</center>");
                text.repaint();
                pj.setPrintable(text.getPrintable(head, foot), pf);
                pj.print();
                System.out.println("done .............. ");
            } catch (PrinterException ex) {
                Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JTable TableRs;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    public javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDiagnosa;
    private javax.swing.JLabel jLabelDokter;
    private javax.swing.JLabel jLabelHasil;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelUmur;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField jumlah;
    public javax.swing.JTextField kode_barang;
    public javax.swing.JTextField nambarang;
    public javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables

//add function list data java 
    //non aktif kan ketika program tidak di eksekusi
    private void SetEditOff() {
        Id.setEnabled(false);
        nambarang.setEnabled(false);
        totalBayar.setEnabled(false);
        harga.setEnabled(false);
        kode_barang.setEnabled(false);
        jumlah.setEnabled(true);
    }

    private void setEditOn() {
        nambarang.setEnabled(true);
        totalBayar.setEnabled(true);

        harga.setEnabled(true);
        kode_barang.setEnabled(true);
        jumlah.setEnabled(true);
    }

    private void tblKeForm() {

        Id.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 0) + "");

        kode_barang.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 1) + "");
        nambarang.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 2) + "");
        harga.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 3) + "");
        jumlah.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 4) + "");
        totalBayar.setText(tabModel.getValueAt(TableRs.getSelectedRow(), 5) + "");

        Id.setEnabled(false);
        jButtonAdd.setEnabled(true);
        jButtonDelete.setEnabled(true);
        jButtonSave.setEnabled(true);
        jButtonUpdate.setEnabled(false);
    }

    private void BersihData() {
        nambarang.setText("");
        totalBayar.setText("");
        harga.setText("");
        kode_barang.setText("");
        jumlah.setText("");
    }

}
